name: Notify Main Repository

on:
  push:
    branches:
      - main  # or whatever branch your submodule uses

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send dispatch event to main repository
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.MAIN_REPO_TOKEN }}" \
            https://api.github.com/repos/chan-ok/knowledge/dispatches \
            -d '{"event_type": "update_submodule"}'
